version: "3.8"
services:
  db_postgres_primary:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: juniorstart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - "postgres_primary:/var/lib/postgresql/data"

  db_postgres_logs:
    build:
      context: postgres_logs_db
      dockerfile: Dockerfile-postgres_logs
    restart: always
    environment:
      POSTGRES_DB: juniorstart_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - "postgres_logs:/var/lib/postgresql/data"

volumes:
  postgres_primary:
  postgres_logs: